# 应用名称
spring.application.name=sqlparser-demo

# 日志配置
logging.level.root=INFO
logging.level.com.lineage.plsql.parser=DEBUG
logging.level.PlSqlParser=WARN
logging.level.PlSqlLexer=WARN
logging.level.org.antlr=WARN

# 日志文件配置
logging.file.name=logs/sqlparser-demo.log
logging.file.max-size=10MB
logging.file.max-history=30
